In [1]:
import datetime
import requests
import json
import os

import matplotlib.pyplot as plt
from dotenv import load_dotenv
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, text, MetaData, Table
from sqlalchemy.orm import sessionmaker

In [2]:
def create_connection():
    """
    Створює підключення через SQLAlchemy
    """
    # Завантажуємо змінні середовища
    load_dotenv()

    # Отримуємо параметри з environment variables
    host = os.getenv('DB_HOST', 'localhost')
    port = os.getenv('DB_PORT', '3306')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = os.getenv('DB_NAME')

    if not all([user, password, database]):
        raise ValueError("Не всі параметри БД задані в .env файлі!")

    # Створюємо connection string
    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"

    # Створюємо engine з connection pooling
    engine = create_engine(
        connection_string,
        pool_size=2,           # Розмір пулу підключень
        max_overflow=20,        # Максимальна кількість додаткових підключень
        pool_pre_ping=True,     # Перевірка підключення перед використанням
        echo=False              # Логування SQL запитів (True для debug)
    )

    # Тестуємо підключення
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT 1"))
            result.fetchone()

        print("✅ Підключення до БД успішне!")
        print(f"🔗 {user}@{host}:{port}/{database}")
        print(f"⚡ Engine: {engine}")

        return engine

    except Exception as e:
        print(f"❌ Помилка підключення: {e}")
        return None

# Створюємо підключення
engine = create_connection()

✅ Підключення до БД успішне!
🔗 root@127.0.0.1:3306/classicmodels
⚡ Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3306/classicmodels)

In [3]:
def update_customer_contact(customer_id, new_phone):
    with engine.begin() as conn:
        check = conn.execute(text("SELECT customerNumber FROM customers WHERE customerNumber = :id"), {"id": customer_id}).fetchone()
        
        if check:
            conn.execute(text("UPDATE customers SET phone = :phone WHERE customerNumber = :id"), 
                         {"phone": new_phone, "id": customer_id})
            print(f"Дані клієнта {customer_id} успішно оновлено.")
        else:
            print(f"Клієнта з номером {customer_id} не знайдено.")

update_customer_contact(103, "+380501234567")
pd.read_sql(text("SELECT customerNumber, customerName, phone FROM customers WHERE customerNumber = 103"), engine)

Дані клієнта 103 успішно оновлено.

   customerNumber       customerName          phone
0             103  Atelier graphique  +380501234567

In [4]:
def create_order_transaction(cust_id, items):
    try:
        with engine.begin() as conn:
            new_id = conn.execute(text("SELECT MAX(orderNumber) + 1 FROM orders")).scalar()
            conn.execute(text("""
                INSERT INTO orders (orderNumber, orderDate, requiredDate, status, customerNumber)
                VALUES (:n, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 7 DAY), 'In Process', :c)
            """), {"n": new_id, "c": cust_id})

            for i, item in enumerate(items, 1):

                stock = conn.execute(text("SELECT quantityInStock FROM products WHERE productCode = :cd"), 
                                     {"cd": item['code']}).scalar()
                
                if not stock or stock < item['qty']:
                    raise Exception(f"Недостатньо товару {item['code']}")

                conn.execute(text("""
                    INSERT INTO orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                    VALUES (:n, :cd, :q, :p, :l)
                """), {"n": new_id, "cd": item['code'], "q": item['qty'], "p": item['price'], "l": i})

                conn.execute(text("UPDATE products SET quantityInStock = quantityInStock - :q WHERE productCode = :cd"),
                             {"q": item['qty'], "cd": item['code']})
            
            print(f"Замовлення №{new_id} створено")
            return new_id
    except Exception as e:
        print(f"Помилка: {e}. Відкат транзакції.")
        return None

test_items = [{'code': 'S10_1678', 'qty': 2, 'price': 95.7}, {'code': 'S10_1949', 'qty': 1, 'price': 150.0}]
oid = create_order_transaction(103, test_items)

if oid:
    display(pd.read_sql(text(f"SELECT * FROM orderdetails WHERE orderNumber = {oid}"), engine))
    display(pd.read_sql(text(f"SELECT * FROM orders WHERE orderNumber = {oid}"), engine))

Замовлення №10426 створено

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10426    S10_1678                2       95.7                1
1        10426    S10_1949                1      150.0                2

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10426,2026-03-15,2026-03-22,None,In Process,None,103